import "../../Styles/globals.scss";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import ClientLayout from "./ClientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `Bin's Space`,
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ko" }];
}

// 유효한 언어 목록
const validLanguages = ["en", "ko"];

export default function Layout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  // 유효하지 않은 언어인 경우 404
  if (!validLanguages.includes(lang)) {
    return null;
  }

  return (
    <html lang={lang}>
      <body className={inter.className}>
        <ClientLayout lang={lang}>{children}</ClientLayout>
        <div id="modal-root" />
      </body>
    </html>
  );
}
